---
- name: Include deploy for Debian systems
  include: http_deb.yaml
  when: ansible_os_family == 'Debian'

- name: Include deploy for RedHat systems
  include: http_rh.yaml
  when: ansible_os_family == 'RedHat'

- name: Copy first page.
  copy: 
    src: index.html
    dest: "{{ default_home }}"
    owner: root
    group: root
    mode: '0775'
  notify:
    - restart apache

- name: Check connection to localhost.
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 3
  register: out
- name: Print out.
  debug:
    msg: "{{ out }}"

- name: Templates.
  template:
    src: "host.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Check template.
  shell: |
    cat /etc/hosts
  register: out1
  changed_when: false

- name: Print out1
  debug:
    msg: "{{ out1.stdout_lines }}"

- name: Check content to the sites.
  uri:
    url: "http://{{ item.name }}"
    return_content: yes
  loop: "{{ virtual_hosts }}"
  register: out2
  failed_when: "'Hi' not in out2.content"
  tags: 
    - tests
- name: Print out.
  debug:
    msg: "{{ out2 }}"
  tags:
    - tests