apt_http_packages:
  - nginx

yum_http_packages:
  - epel-release
  - nginx

example_home: "/var/www/example.com/html"
test_home:  "/var/www/test.com/html"

sites: "/etc/nginx/sites-available"

site_deb: "local-deb.site"
site_rh: "local-rh.site"
site_example: "example.com"
site_test: "test.com"

virtual_hosts:
#  - { name: "{{ site_deb }}", ip: "{{ hostvars[\"work_01\"].ansible_host }}"}
#  - { name: "{{ site_rh }}", ip: "{{ hostvars[\"workshop_01\"].ansible_host }}"}
  - { name: "{{ site_example }}", ip: "{{ hostvars[\"workshop_01\"].ansible_host }}"}
  - { name: "{{ site_test }}", ip: "{{ hostvars[\"workshop_01\"].ansible_host }}"}